name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential -y

      - name: Build
        run: |
          go build -o myapp .

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            kill -9 $(lsof -t -i:8080) || true
            scp myapp ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USERNAME }}/
            ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'nohup /home/${{secrets.SERVER_USERNAME}}/myapp > /dev/null 2>&1 &'