name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential -y

      - name: Build
        run: |
          go build -o myapp .

      - name: Get Host and Port
        id: host_and_port
        run: |
          HOST_WITH_PORT="${{ secrets.SERVER_HOST_WITH_PORT }}"
          IFS=":" read -ra HOST_AND_PORT <<< "$HOST_WITH_PORT"
          echo "Host: ${HOST_AND_PORT[0]}"
          echo "Port: ${HOST_AND_PORT[1]}"
        shell: bash

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ steps.host_and_port.outputs.Host }}
          port: ${{ steps.host_and_port.outputs.Port }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            kill -9 $(lsof -t -i:8080) || true
            scp -P 58022  myapp ${{ secrets.SERVER_USERNAME }}@${{ steps.host_and_port.outputs.Host }}:/home/${{ secrets.SERVER_USERNAME }}/
            ssh ${{ secrets.SERVER_USERNAME }}@${{ steps.host_and_port.outputs.Host }} -p 58022 'nohup /home/${{secrets.SERVER_USERNAME}}/myapp > /dev/null 2>&1 &'